name: Deploy to ECS

on:
  push:
    branches:
      - main

permissions:
  id-token: write 
  contents: read  

# Define the variables here so the pipeline has them instantly
env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: ai-log-analyzer-cluster
  SERVICE_NAME: ai-log-analyzer-service
  ECR_REPOSITORY: ai-log-analyzer

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 1: Securely authenticate using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::287084411936:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      # Step 2: Login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Step 3: Build and push the image using the env variables
      - name: Build, tag, and push image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG -f docker/Dockerfile .
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

      # Step 4: Tell ECS to grab the new image
      - name: Force new ECS deployment
        run: |
          aws ecs update-service \
            --cluster ${{ env.CLUSTER_NAME }} \
            --service ${{ env.SERVICE_NAME }} \
            --region ${{ env.AWS_REGION }} \
            --force-new-deployment